### ISSUE TITLE
ESP32-C3-LCDkit missing encoder input?

### ISSUE THREAD

**Issue by modi12jin** [Lzw655/ESP32_Display_Panel#1]
@Lzw655 Hello! Is the LVGL example missing an input device encoder?

![103091_1691126540_hd](https://github.com/Lzw655/ESP32_Display_Panel/assets/40233017/b7cc0951-83f0-4814-a5cd-48bd4b496780)

You seem to have forgotten to explain that the demos folder in LVGL should be pasted into the src folder.

![2023-08-04_13-43](https://github.com/Lzw655/ESP32_Display_Panel/assets/40233017/b038652a-eb2b-4843-a4c6-94fecd62e345)

`#include "demos/lv_demos.h"`

**Comment by Lzw655** [comment]
Wow,  you may be the first one to use this library. Thank you for supporting.

I have provided instructions on how to use LVGL demos [here](https://github.com/Lzw655/ESP32_Display_Panel/blob/c5b47729ea8098485a69cee8738811442c153b35/examples/LVGL/ESP32-C3-LCDkit/ESP32-C3-LCDkit.ino#L65).  However, it's true that the information here is not complete. I will improve it and thank you for the feedback.

As for the input devices, this library doesn't support them yet, but I will add LVGL Porting in the next version.

**Comment by modi12jin** [comment]
After your reminder, I just realized I missed it.
