### ISSUE TITLE
S3 LCD EV Board with Arduino IDE

### ISSUE THREAD

**Issue by ladyada** [Lzw655/ESP32_Display_Panel#4]
hiya, i wanted to try programming the LCD EV board with the default square 480x480 TFT in Arduino IDE - the library example for RGB bars compiles and uploads and there's correct looking bits coming out of the IO expander SPI port & TTL RGB data that looks good on the main port - but nothing appears on the TFT (just the backlight is on, and it had the boot demo working out of the box)

its ok if it doesn't work, but there could also be something simple i'm missing?

ESP_Panel_Conf.h looks like this:
![image](https://github.com/Lzw655/ESP32_Display_Panel/assets/1214161/946de1dc-5ce5-481a-946f-0d2348a26c33)

and tools menu looks like this:
![image](https://github.com/Lzw655/ESP32_Display_Panel/assets/1214161/f2c8b565-5ff8-4125-a010-262633a6ce7b)

and serial output is:
```
21:56:21.800 -> ESP-ROM:esp32s3-20210327
21:56:21.800 -> Build:Mar 27 2021
21:56:21.800 -> rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
21:56:21.800 -> SPIWP:0xee
21:56:21.800 -> mode:DIO, clock div:1
21:56:21.800 -> load:0x3fce3808,len:0x44c
21:56:21.800 -> load:0x403c9700,len:0xbe4
21:56:21.800 -> load:0x403cc700,len:0x2a68
21:56:21.800 -> entry 0x403c98d4
21:56:21.943 -> [   132][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
21:56:21.943 -> Hello Arduino!
21:56:21.943 -> I am ESP32_Display_Panel.
21:56:21.943 -> Initialize panel
21:56:23.502 -> Draw color bar from top to bottom, the order is B - G - R
21:56:23.555 -> Setup done
21:56:23.555 -> Loop
21:56:24.540 -> Loop
```

do you know if `ESP_PANEL_BOARD_ESP32_S3_LCD_EV_BOARD` was verified to work in Arduino? or i could try it out in just the IDF if that's the only place its recommended.

thanks for any advice! if we can't get it working, we'll just try writing a library from scratch

**Comment by Lzw655** [comment]
Hi @ladyada, I have tested `ESP_PANEL_BOARD_ESP32_S3_LCD_EV_BOARD` with Arduino and it worked well. 

Did you test the board hardware is good? Like, upload the factory bin.

**Comment by Lzw655** [comment]
@ladyada Oh, I know the reason now. The board I used is an old version and the newest version should set the level of **GPIO3** (ESP_PANEL_LCD_RGB_IO_VSYNC) to high before initialization as following code:

```c
#ifdef ESP_PANEL_BOARD_ESP32_S3_LCD_EV_BOARD
    /* Initialize IO expander */
   ...
    /* For the newest version sub board, need to set `ESP_PANEL_LCD_RGB_IO_VSYNC` to high before initialize LCD */
    pinMode(ESP_PANEL_LCD_RGB_IO_VSYNC, OUTPUT);
    digitalWrite(ESP_PANEL_LCD_RGB_IO_VSYNC, HIGH);
#endif
```

**Comment by Lzw655** [comment]
@ladyada There are some bugs in the *master* branch. You can try the *bugfix/remove_hal_spi_ll_header* branch and I'll release it after Arduino Library Registry approves my operation of renaming. After all, the library can be downloaded directly from Arduino IDE.

**Comment by ladyada** [comment]
awesome - thanks i just tried it and it works wonderful now :)

![image](https://github.com/Lzw655/ESP32_Display_Panel/assets/1214161/1b6e4626-bfc4-4411-a3c5-c57f77827cc3)

**Comment by Lzw655** [comment]
BTW, since the current version of IDF used in Arduino (v2.0.11) is v4.4.5, developing with this version for RGB LCD may yield poor results as it lacks the ability to enable certain high-performance configurations such as `PSRAM DDR 120M`, `COMPILER_OPTIMIZATION_PERF`, and more. 

Furthermore, it's prone to [screen drifting issues](https://docs.espressif.com/projects/esp-faq/en/latest/software-framework/peripherals/lcd.html#why-do-i-get-drift-overall-drift-of-the-display-when-driving-an-rgb-lcd-screen). 

In the future, I plan to attempt compiling the highest-performance Arduino-ESP version based on IDF v5.0 (or v5.1).

**Comment by ladyada** [comment]
good to know - cc @jepler this may be important details!

also meanwhile i got ST7701S 2.1" round capacitive display working

![image](https://github.com/Lzw655/ESP32_Display_Panel/assets/1214161/caaf2196-b826-4cb4-b7cf-6aa6e1343d13)

here is the init seq

```
// *INDENT-OFF*
const static lcd_init_cmd_t vendor_specific_init[] = {
    {0xFF, {0x77, 0x01, 0x00, 0x00, 0x10}, 5},
    {0xC0, {0x3b, 0x00}, 2},
    {0xC1, {0x0B, 0x02}, 2},
    {0xC2, {0x00, 0x02}, 2},
    {0xCC, {0x10}, 1},
    {0xCD, {0x08}, 1},
    {0xB0, {0x02, 0x13, 0x1B, 0x0D, 0x10, 0x05, 0x09, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D}, 16},
    {0xB1, {0x05, 0x13, 0x1B, 0x0D, 0x11, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D}, 16},

    {0xff, {0x77, 0x01, 0x00, 0x00, 0x11}, 5},
    {0xb0, {0x5D}, 1},
    {0xb1, {0x43}, 1},
    {0xb2, {0x81}, 1},
    {0xb3, {0x80}, 1},
    {0xb5, {0x43}, 1},
    {0xb7, {0x85}, 1},
    {0xb8, {0x20}, 1},
    {0xC1, {0x78}, 1},
    {0xC2, {0x78}, 1},
    {0xD0, {0x88}, 1},

    {0xE0, {0x00, 0x00, 0x02}, 3},
    {0xE1, {0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20}, 11},
    {0xE2, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 13},
    {0xE3, {0x00, 0x00, 0x11, 0x00}, 4},
    {0xE4, {0x22, 0x00}, 2},
    {0xE5, {0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 16},
    {0xE6, {0x00, 0x00, 0x11, 0x00}, 4},
    {0xE7, {0x22, 0x00}, 2},
    {0xE8, {0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 16},
    {0xEB, {0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00}, 7},
    {0xED, {0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF}, 16},
    {0xEF, {0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F}, 6},

    {0xff, {0x77, 0x01, 0x00, 0x00, 0x13}, 5},
    {0xEF, {0x08}, 1},

    {0xff, {0x77, 0x01, 0x00, 0x00, 0x00}, 5},

    {0x29, {0x00}, 0},
    {0x36, {0x00}, 1},
    {0x3A, {0x60}, 1},

    {0x11, {0x00}, 0},
    {0x00, {0x00}, 0xff},
};
```

**Comment by Lzw655** [comment]
@ladyada This library v1.1.1 can be directly downloaded from Arduino IDE now. If you have any problems or any requests, please let me know. Thank you very much!

**Comment by ladyada** [comment]
thank you kindly - its a great library. thank you so much for supporting the EV board :)

**Comment by Lzw655** [comment]
You're welcome. It's part of my job. And It's welcome to contribute your drivers and boards to the library. I'll write the guide for this section as soon as possible.
